### PR TITLE
Implement i128/u128 deserialization

### PR DESCRIPTION
**Pull request by gpollo**

### CODE REVIEW

**Review by ahl — COMMENTED** [review]
looks good; worth adding a test?

**Comment by gpollo** [comment]
Yeah, the `u128` works well, but not the `i128`. It doesn't like the negative (`-`) sign on some test cases. Tried de-serializing other types (e.g. `i32`) and got the same error. Do you know if negative numbers are properly handled in the library?

**Comment by gpollo** [comment]
Okay, I've tried implementing negative number handling, please have a look. All tests passed.

**Comment by ahl** [comment]
Nope! negative numbers are totally broken. How embarrassing. Fix coming shortly.

**Comment by ahl** [comment]
Try now after merging with #96? Thanks again.

**Comment by gpollo** [comment]
Works, but there is a small problem. This line https://github.com/oxidecomputer/serde_tokenstream/blob/main/src/serde_tokenstream.rs#L205

From what I understand, we parse as a positive number, then negate it. The problem is that `-i32::MAX != i32::MIN`, but `-i32::MAX-1 == i32::MIN` (there a difference of 1). This means that `field = -2147483648` will fail if `field: i32` even thought `-2147483648` is a valid signed 32-bit numbers.

See the current PR, I parse both the punctuation and the literal as one stream and this case is taken care of.

**Comment by ahl** [comment]
Wow. I shouldn't be allowed to use integers. I'm going to crib your method.

**Comment by ahl** [comment]
Can you please take a look at #97?

**Review by ahl — APPROVED** [review]
Awesome. Thanks! I'll get a new release published soon.

Are you using this for something?

**Pull request merged**
